### ISSUE TITLE
Merge to homebrew-core

### ISSUE THREAD

**Issue by dawidd6** [osx-cross/homebrew-avr#123]
Is it possible to merge this tap to `homebrew/homebrew-core`?
Is it something you would like to do or not and why?

**Comment by ladislas** [comment]
avr-gcc is a very specific use of gcc with a lot of specific flags. brew is trying to move away from specific options and provide software that is usable for everyone.

a bottle allows us to do what we want, to change often and to not go through the review process of core each time.

so no, there is no plan to merge this with core :)
