### ISSUE TITLE
macOS 10.15 Catalina Support

### ISSUE THREAD

**Issue by andrewlvovsky** [osx-cross/homebrew-avr#129]
Not sure if this is where I should ask, but is there a timeline for Catalina support?

**Comment by ladislas** [comment]
as soon as it's available in Azure Pipelines.

for the moment you can compile from source. it should take around 40 minutes on a MacBook Pro Retina, 13-inch, Early 2015.

**Comment by ladislas** [comment]
FYI -- https://github.com/microsoft/azure-pipelines-image-generation/issues/1277#issuecomment-539598428

**Comment by ladislas** [comment]
@borninla I just upgraded to Catalina with a clean install and when running `brew install avr-gcc` it installed the Mojave bottle without any issues.

Seems to be working fine for the moment.

as soon as Azure Pipelines adds Catalina support, I'll update the build process.
