### ISSUE TITLE
Needs explicit path directives on avr-gcc 4.9.3

### ISSUE THREAD

**Issue by jj1bdx** [osx-cross/homebrew-avr#14]
After upgrading to avr-gcc 4.9.3, I have to set the following compilation flags for ATmega328p, which were not required in the previous version. Could this be automated in somewhere else or should this be done always in this way?

```
COMMON += -I/usr/local/Cellar/avr-libc/1.8.1/avr/include
COMMON += -L/usr/local/Cellar/avr-libc/1.8.1/avr/lib
COMMON += -L/usr/local/Cellar/avr-binutils/2.25/avr/lib
COMMON += -B/usr/local/Cellar/avr-libc/1.8.1/avr/lib/avr5
```

**Comment by ladislas** [comment]
did you upgrade from 4.8?

before upgrading you should `brew remove avr-gcc avr-binutils avr-libc`.

**Comment by jj1bdx** [comment]
@ladislas removing and installing the avr-gcc toolchain solved the problem. Thanks!

**Comment by ladislas** [comment]
you're welcome :)

when installing, you need to compile avr-libc with the version of gcc you want to use. that's why just installing avr-gcc doesn't work ;)
