### ISSUE TITLE
GCC 10 is out

### ISSUE THREAD

**Issue by luqasz** [osx-cross/homebrew-avr#189]
Hi. 

Can you please update formula for new [GCC 10 ](https://gcc.gnu.org/gcc-10/changes.html) ?

**Comment by ladislas** [comment]
It's quite a big release and it's so fresh, I'm considering adding it as a `version` with `avr-gcc@10` to give people time to hop in and test it.

when it becomes clear that it doesn't bring new bugs to avr, I'll move it to the main version.

**Comment by luqasz** [comment]
Sure. No problem. Just a note.
