### ISSUE TITLE
avr-gcc@8 has no atmega32u4 libraries

### ISSUE THREAD

**Issue by w-A-L-L-e** [osx-cross/homebrew-avr#207]
After doing a brew update, I ran into an issue with avr-gcc vs 9.3.0 it doesnt compile a library called micro-ecc anymore (first tried avr-gcc@10 also gave same error).
The error is:
```
micro-ecc/asm_avr.inc:255:9: error: size of string literal is too large
```
Which is basically a loop-unrolled asm function (and therefor a long string with asm instructions). 

So I tried installing avr-gcc@8 and then linked it as default. Now it does compile all my c and asm files for my project (including no more errors on the asm_avr.inc file). But when it starts linking I get these missing library errors:
```
/usr/local/opt/avr-binutils/bin/avr-ld: cannot find crtatmega32u4.o: No such file or directory
/usr/local/opt/avr-binutils/bin/avr-ld: cannot find -latmega32u4
```

**Comment by ladislas** [comment]
yes, everything is broken, see #204
will fix soon

**Comment by ladislas** [comment]
Can you brew remove avr-gcc@9 and brew install again? it should be fixed :)

**Comment by ladislas** [comment]
avr-gcc@8/9/10 are now available and working fine. I'll close the issue. Feel free to reopen or create a new one if needed.
