### ISSUE TITLE
avr-project in homebrew-avr?

### ISSUE THREAD

**Issue by voltangle** [osx-cross/homebrew-avr#214]
As in title

**Comment by ladislas** [comment]
Can you be a little more precise?

**Comment by voltangle** [comment]
So, I think a project called x-avr uses avr-project tool to make Xcode projects for AVR. But when I uninstalled CrossPack and installed homebrew-avr, there was no avr-project. And I think that was the cause of x-avr failing to generate a proper project

**Comment by ladislas** [comment]
ah! I already had this kind of question in the past. See #131 & #132.

avr-project and osx-cross/avr are not related in any way, I've never ever used avr-project, nor crosspack, nor xcode templates for avr in my life, so I can't really help you.

If you think they or documentation could be added to this repo, you can open a PR and we'll discuss it.

**Comment by voltangle** [comment]
I understand, thanks for replying :D
