### ISSUE TITLE
Request for adding avra(assembly compiler) to the formulae

### ISSUE THREAD

**Issue by voltangle** [osx-cross/homebrew-avr#221]
As in the title, can you add `avra`, the AVR assembly compiler, to the `homebrew-avr` formulae?

**Comment by ladislas** [comment]
I don't know what it is but I'll be happy to review a PR.

**Comment by voltangle** [comment]
Basically it is `avr-gcc`, but for Assembly, called `avra` for AVR Assembly. I'll create a PR with `avra` included :D

**Comment by ladislas** [comment]
@GGorAA any news?

**Comment by voltangle** [comment]
Ohh, I'm sorry, I completely forgot about it :D
When I will find time I will create a PR :)

**Comment by voltangle** [comment]
Sorry, I just realised that I actually don't know how to add a bottle to the formulae :(

**Comment by ladislas** [comment]
You don't have to, the CI will do it for you. I just need the PR.

**Comment by voltangle** [comment]
I mean, how to add avra compiler to the formulae, I have no idea where to place it

**Comment by ladislas** [comment]
You can use the simavr formula as a template: https://github.com/osx-cross/homebrew-avr/blob/master/Formula/simavr.rb

Steps:

1. fork this repository
2. create a new branch with a name like `GGorAA/formula/add-avra`
1. create a new file in `Formula` named `avra.rb`
2. copy the content of the simavr formula
3. fill in the details: `desc`, `homepage`, `url`, etc.
4. if there are some dependencies, you can define them with `depends_on`
5. in the `def install ... end` bloc, add the commands to run to build avra like you would do on your computer
6. commit your changes and push them
7. open a PR here and I'll review

**Comment by voltangle** [comment]
Thanks for the explanation!

**Comment by bartekpacia** [comment]
I'll try to do this:)

**Comment by ladislas** [comment]
closing as won't fix for the moment. Feel free to reopen #235 in the future if needed.
