### ISSUE TITLE
Cannot build avr-gcc on M1 ARM based Mac

### ISSUE THREAD

**Issue by jknoetzke** [osx-cross/homebrew-avr#222]
➜  ~  brew tap osx-cross/avr
➜  ~ brew install avr-gcc
==> Installing avr-gcc from osx-cross/avr
avr-gcc: The x86_64 architecture is required for this software.
Error: An unsatisfied requirement failed this build.

**Comment by ladislas** [comment]
yes, same as #220 

I'm happy to review a PR but I don't own an M1 so I can work it out.
