### ISSUE TITLE
arm64 support / M1

### ISSUE THREAD

**Issue by braindaddy73** [osx-cross/homebrew-avr#232]
Hi there,

is it possible to build the toolchain for the new M1?

Thx
Heiko

**Comment by ladislas** [comment]
Unfortunately not yet. We do not have access to any M1 Macs. But it should work as is with Rosetta 2

**Comment by braindaddy73** [comment]
Okay I will try. It didn't install because of required architecture. But I am new to homebrew and perhaps I find a way. :P Perhaps by time i will try to compile from source. To much work at the moment ...

Many thanks so far 👍

**Comment by ladislas** [comment]
Try the simplest version first. It should work without the need to recompile from source.

**Comment by braindaddy73** [comment]
Ok, works like a charm. Had to install the homebrew-prefix for x86_64 first. Then point to the right brew installation:

arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
arch -x86_64 /usr/local/bin/brew tap osx-cross/avr
arch -x86_64 /usr/local/bin/brew install avr-gcc
arch -x86_64 /usr/local/bin/brew install avr-gdb

Thx for help!
