### ISSUE TITLE
Support for avr-gcc 11

### ISSUE THREAD

**Issue by bartekpacia** [osx-cross/homebrew-avr#233]
As the title says. Will (if yes, then when?) `avr-gcc@11` be available?

**Comment by ladislas** [comment]
GCC 11 is supposed to remove support for AVR, so I don't know. I'm open to a PR if you want to try.

https://www.phoronix.com/scan.php?page=news_item&px=GCC-11-Dropping-CC0

**Comment by bartekpacia** [comment]
Hmmm, that link you gave is interesting, even more given the fact that yesterday I installed `avr-gcc` on my Windows machine from [this website](https://blog.zakkemble.net/avr-gcc-builds/). It is v11.1.0 and works just fine.
[Here](https://www.lumito.net/2021/04/28/released-avr-gcc-11-1-0/) it also appears that `avr-gcc` v11 indeed exists.
I'll try to make a PR:)

**Comment by ladislas** [comment]
That's great news then. I don't have much time currently to add the formula but I can review a PR. You can look at the commit history for examples.

Also look at how they do it here: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gcc.rb
