### ISSUE TITLE
URL for ATMega168pbSupport-Patch is forbidden

### ISSUE THREAD

**Issue by Feuerwerk** [osx-cross/homebrew-avr#245]
Hi,

Installing avr-gcc with --with-ATMega168pbSupport activated one will get a 403 forbidden error when home-brew try to download the patch https://dl.bintray.com/osx-cross/avr-patches/avr-libc-2.0.0-atmega168pb.patch

**Comment by ladislas** [comment]
Yes, bintray has closed its doors...
We should move the patch here, could you make a PR? :)

https://github.com/osx-cross/homebrew-avr/tree/master/Patch

**Comment by ladislas** [comment]
ideally, we would add the patch in a first PR, then reference the patch raw link in another PR.

**Comment by Feuerwerk** [comment]
Can't we reference https://github.com/osx-cross/homebrew-avr/blob/master/Patch/avr-binutils-size.patch directly?
Whats the benefit to reference the patch inside a PR?

Just for clarification how this is working:
- I create a PR which only includes the patch
- This PR is rejected
- Then i create a second PR updating the brew-receipt referencing to the patch inside the first PR

Is that correct?

**Comment by ladislas** [comment]
> Can't we reference https://github.com/osx-cross/homebrew-avr/blob/master/Patch/avr-binutils-size.patch directly?
> 
> Whats the benefit to reference the patch inside a PR?

I don't think it's the same patch. The one already here is just for size in binutils but it actually not used. 


> Just for clarification how this is working:
> 
> - I create a PR which only includes the patch
> 
> - This PR is rejected
> 
> - Then i create a second PR updating the brew-receipt referencing to the patch inside the first PR
>
> Is that correct?

The first PR will be accepted and merged. Then you can use the reference from master for the second PR

**Comment by Feuerwerk** [comment]
Ahhh, ok, got it. I think i still have the original (small) patch, i need to have a look and than create the PR
