### ISSUE TITLE
Unable to install simavr

### ISSUE THREAD

**Issue by voltangle** [osx-cross/homebrew-avr#256]
![image](https://user-images.githubusercontent.com/61655029/129614571-5b9fc972-5409-45a9-9dd6-c1d3472caa0f.png)
It failed with this issue
Possibly markups from git merge conflict resolve UI somehow ended up here

**Comment by ladislas** [comment]
It looks like a local issue. As you can see, the formula has no `<<<<<<` https://github.com/osx-cross/homebrew-avr/blob/68632955c4d9e9173204df53b29e6c2a36ae4b52/Formula/simavr.rb

Try removing the tap and using brew tap again.

**Comment by voltangle** [comment]
Yea, it did was a local issue. By untapping and tapping the repo and trying to install again the issue has gone away
