### ISSUE TITLE
cc1: internal compiler error: Illegal instruction: 4

### ISSUE THREAD

**Issue by leElvyn** [osx-cross/homebrew-avr#261]
## Hardware : 
MacBook, aluminum late 2008
Macos 10.15.7 (19H2)
## avr brew version : 
osx-cross/avr/avr-gcc@9: stable 9.3.0 (bottled), HEAD

I am trying to compile one of my project (https://github.com/leElvyn/auto-smash/tree/main/firmware) from my macos computer. Usually, i am using my main computer to do that, a windows PC with WSL ubuntu, and it is working perfectly, but when using my macos computer : 

```
 [INFO]    : Begin compilation of project "src/Joystick"...

avr-gcc (Homebrew AVR GCC 8.4.0_2) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 [GCC]     : Compiling C file "Joystick.c"
avr-gcc -c -pipe -gdwarf-2 -g2 -mmcu=atmega32u4 -fshort-enums -fno-inline-small-functions -Wall -fno-strict-aliasing -funsigned-char -funsigned-bitfields -ffunction-sections -I. -DARCH=ARCH_AVR8 -DDMBS_ARCH_AVR8 -mrelax -fno-jump-tables -x c -Os -std=gnu99 -Wstrict-prototypes -DF_CPU=16000000UL -DUSE_LUFA_CONFIG_HEADER -IConfig/ -I/home/red/arduino-1.8.16/hardware/tools/avr/avr/include/ -mmcu=atmega32u4  -I. -I./lufa/LUFA/.. -DARCH=ARCH_AVR8 -DBOARD=BOARD_NONE -DF_USB=16000000UL   -MMD -MP -MF obj/Joystick.d src/Joystick.c -o obj/Joystick.o
cc1: internal compiler error: Illegal instruction: 4
libbacktrace could not find executable to open
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/osx-cross/homebrew-avr/issues> for instructions.
make: *** [obj/Joystick.o] Error 1
```

**Comment by ladislas** [comment]
I can't compile your project as modules are missing and the commands in the readme don't work for me.

Can you try a simple program?
Are you up to date with Xcode and the command line tools?

**Comment by leElvyn** [comment]
Yeah, sorry, LUFA is required to build this : http://www.fourwalledcubicle.com/LUFA.php (downloads can be found here)
I tried this minimal program : https://www.cs.colby.edu/maxwell/courses/tutorials/maketutor/ (i took the first one i could find)
And it compiled an ran without any problems

How can i check if CLI tools and xcode are up to date ?

**Comment by ladislas** [comment]
@leElvyn Were you able to fix your issue? 

Closing for now, feel free to reopen if needed.
