### ISSUE TITLE
Support for newer MCUs

### ISSUE THREAD

**Issue by lukeadair** [osx-cross/homebrew-avr#266]
The version of avr-libc (2.0.0) that is currently used does not support newer MCUs like the attiny1616, but they recently released 2.1.0 that does support them.

Please consider updating this to use the latest version found here:
https://github.com/avrdudes/avr-libc/blob/main/NEWS

**Comment by ladislas** [comment]
Ah! thanks for letting me know, let's see if it works :) https://github.com/osx-cross/homebrew-avr/pull/267

**Comment by lukeadair** [comment]
Awesome! That was fast. Looks like it failed though.

**Comment by ladislas** [comment]
@lukeadair I've tried with gcc@9 & gcc@10 with no success. I don't have time to investigate locally.

If you can give it a try and report any findings, it would be greatly appreciated.

**Comment by ladislas** [comment]
This has been fixed thanks to @fauxpark 

see #267 & #274
