### ISSUE TITLE
Push avr168pb patch to avr-libc

### ISSUE THREAD

**Issue by ladislas** [osx-cross/homebrew-avr#268]
@Feuerwerk avr-libc now has a new github repo, I think you could push your patch there!

**Comment by Feuerwerk** [comment]
Hi @ladislas 
Thanks for the info, i will have a look and will post here if i have some news.

**Comment by luqasz** [comment]
@ladislas searching github for `avr-libc` returns multiple results. Which repo you refer to ?

**Comment by ladislas** [comment]
here: https://github.com/avrdudes/avr-libc

**Comment by ladislas** [comment]
@luqasz @Feuerwerk any news on that? :)

**Comment by Feuerwerk** [comment]
@ladislas Uuuu, sorry completely forgot about this one. I have to look
