### ISSUE TITLE
Catalina bottles not being built

### ISSUE THREAD

**Issue by fauxpark** [osx-cross/homebrew-avr#270]
`macos-latest` has been updated to macOS 11 (https://github.com/actions/virtual-environments/pull/4048). As a result, only the Big Sur bottle for avr-binutils 2.38 was built.

**Comment by fauxpark** [comment]
Hi @ladislas, any update on this? Sorry to bother.

**Comment by ladislas** [comment]
I'm afraid there's nothing I/we can do about that. 
Unless you have a machine still running Catalina that you want to setup for CI, Catalina users will need to build the packages from source.

That being said, Big Sur is compatible with "very old" computers (see https://support.apple.com/en-us/HT211238) and Catalina is not supported anymore even for security fixes. I would encourage users to upgrade.

**Comment by ladislas** [comment]
Wait, it seems that Catalina is still available! (?)

https://github.com/actions/virtual-environments

**Comment by fauxpark** [comment]
Yes, that's what I was about to post. They've only changed `macos-latest` to point to Big Sur; Catalina hasn't been dropped (yet).

**Comment by ladislas** [comment]
fixed.

**Comment by fauxpark** [comment]
Thanks!
