### ISSUE TITLE
ATTiny828 not supported

### ISSUE THREAD

**Issue by nisheethlahoti** [osx-cross/homebrew-avr#33]
avr-gcc-4.9.3 does not support attiny828 in mmcu options
Note: The included C files do have the required support (accessible with `#define __AVR_ATtiny828__`), but the command line tool seems to be missing it.

**Comment by ladislas** [comment]
@nisheethlahoti did you find a solution?

**Comment by nisheethlahoti** [comment]
It seems to be fixed in the latest version of avr-gcc

**Comment by ladislas** [comment]
perfect :)
