### ISSUE TITLE
avr-libc49 formula broken

### ISSUE THREAD

**Issue by MrLavender** [osx-cross/homebrew-avr#37]
Tries to install in avr-gcc48/4.8.5 instead of avr-gcc49/4.9.3

==> copying /usr/local/Cellar/avr-libc49/2.0.0/avr -> /usr/local/Cellar/avr-gcc48/4.8.5
Error: No such file or directory - /usr/local/Cellar/avr-gcc48/4.8.5

**Comment by ladislas** [comment]
fixed with https://github.com/osx-cross/homebrew-avr/commit/6b281693a4810e33539ea185139cfaed99fbdfc7
