### ISSUE TITLE
6.3.0 doesn't have pgmspace.h

### ISSUE THREAD

**Issue by adzenith** [osx-cross/homebrew-avr#49]
I'm trying to compile [QMK](https://github.com/qmk/qmk_firmware). It used to work fine with 6.2.0, but it looks like 6.3.0 is missing a required header.
6.2.0 had this file:
`/usr/local/Cellar/avr-gcc/6.2.0/avr/include/avr/pgmspace.h`
6.3.0 appears to have no equivalent. Am I doing something wrong? I just `brew update`d.

Thanks!

**Comment by ladislas** [comment]
you have to recompile everything from scratch, specifically avr-libc

**Comment by larsimmisch** [comment]
It would be nice if we could trigger this automatically, but I thought about it a while back and had no good idea how to do it without resorting to very hacky workarounds

**Comment by ladislas** [comment]
this is linked to the fact that we cannot have two versions available at the same time.

someone was talking about sandboxing at some points, it might help solve the problem, but I'm not an expert with homebrew. any ideas?

**Comment by ladislas** [comment]
@larsimmisch i'm gonna try that when i get time: https://github.com/cosmo0920/homebrew-avr/blob/e2d70836645309705df172ba0f2e96b5807fef4e/avr-gcc.rb with the `resource` thing

**Comment by adzenith** [comment]
Just to confirm my understanding, it's as simple as:
```
brew uninstall avr-libc
brew install avr-libc
```
Is that correct?

**Comment by larsimmisch** [comment]
Yes, that should do it.

**Comment by adzenith** [comment]
Thanks for the help - it worked great. I'm gonna go ahead and close this.
