### ISSUE TITLE
avr-gcc 7.1.0 will not find <avr/io.h>

### ISSUE THREAD

**Issue by ubidefeo** [osx-cross/homebrew-avr#55]
just updated but had to `brew switch avr-gcc 6.3.0` to have my code compile again.

```
Compiling C: main.c
avr-gcc -c -mmcu=atmega8515 -I. -gdwarf-2  -Os -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -Wall -Wstrict-prototypes -Wa,-adhlns=./main.lst  -std=gnu99 -MMD -MP -MF .dep/main.o.d main.c -o main.o
main.c:34:10: fatal error: avr/io.h: No such file or directory
 #include <avr/io.h>
          ^~~~~~~~~~
compilation terminated.
make: *** [main.o] Error 1
```

**Comment by ddavidebor** [comment]
same issue here with gcc 7, on a project that compiles correctly on Arch with the same avr-gcc version

**Comment by ladislas** [comment]
you need to recompile avrlibc for each avr version.

this is fixed in branch https://github.com/osx-cross/homebrew-avr/tree/update-7.1-6.4

will merge soon to master

**Comment by codmpm** [comment]
Having the problem right now. How can I use the update-7.1-6.4 version?

**Comment by ladislas** [comment]
@codmpm navigate to `/usr/local/Homebrew/Library/Taps/osx-cross/homebrew-avr/` and switch branch

**Comment by codmpm** [comment]
Thank you!

But sadly I only have a master branch:
![bildschirmfoto 2017-08-04 um 11 14 30](https://user-images.githubusercontent.com/9745239/28962484-2397760c-7906-11e7-8876-60af9a2668ca.png)

**Comment by ladislas** [comment]
@codmpm i just merge the changes, brew update should pull them and it should work. if not untap and tap again ;) 

and as for only seeing the master branch, I had the same issue, you need to:

`git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"`

fixed it for me :)

**Comment by codmpm** [comment]
That did the trick - thank you!

![bildschirmfoto 2017-08-04 um 11 22 50](https://user-images.githubusercontent.com/9745239/28962837-4b5e2662-7907-11e7-8046-d36df14decd9.png)

**Comment by codmpm** [comment]
Sorry to bother you again... but I think I've messed something up:

![bildschirmfoto 2017-08-04 um 11 27 24](https://user-images.githubusercontent.com/9745239/28963040-f83ea23a-7907-11e7-8756-6bf26330b798.png)

**Comment by ladislas** [comment]
oh sorry! I have to update the readme. You just need to run `brew install avr-gcc` :)

**Comment by ladislas** [comment]
but as said, it is now merged in master, so no need to switch branches.

**Comment by codmpm** [comment]
It is working from master. Thank you so much!
