### ISSUE TITLE
404 Not Found when downloading avr-binutils-patch

### ISSUE THREAD

**Issue by Chinchila01** [osx-cross/homebrew-avr#56]
I get the following error when I try to brew install avr-gcc:

`==> Downloading https://raw.githubusercontent.com/osx-cross/homebrew-avr/update-

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "avr-binutils--patch"
Download failed: https://raw.githubusercontent.com/osx-cross/homebrew-avr/update-formula/avr-binutils-size.patch`

**Comment by ladislas** [comment]
@Chinchila01 just fixed it
