### ISSUE TITLE
Missing avr-libc breaks simavr formula

### ISSUE THREAD

**Issue by porglezomp** [osx-cross/homebrew-avr#58]
```
~ $ brew install --HEAD simavr
==> Installing simavr from osx-cross/avr
Error: No available formula with the name "avr-libc" (dependency of osx-cross/avr/simavr)
==> Searching for a previously deleted formula...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```
I suspect this was caused by #54 removing the `avr-libc` formula, and not changing `simavr` to use the resource, but I don't know how to test with a local formula to confirm this.

**Comment by ladislas** [comment]
I just created a PR with the fix - https://github.com/osx-cross/homebrew-avr/pull/59

Can you try it? 

how to here: https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by ladislas** [comment]
well... doesn't seem to work... 

@obra @jacquesg - any ideas guys on what we should do?

**Comment by porglezomp** [comment]
Hm, I was messing around working with it locally, and accidentally got it to run fine with the same package after I installed `avr-gcc` first. I had a few broken steps in between, so I'm not sure if that's all that's changed. Does setting `simavr` to depend on `avr-gcc` work?

**Comment by porglezomp** [comment]
Hm, I was messing around working with it locally, and accidentally got it to run fine with the same package after I installed `avr-gcc` first. I had a few broken steps in between, so I'm not sure if that's all that's changed. Does setting `simavr` to depend on `avr-gcc` work?

**Comment by ladislas** [comment]
yep that might be it! 

I'll edit the PR

**Comment by ladislas** [comment]
Just merged the changes. it's working now and pulling avr-gcc as a resource which contains avr-libc and avr-binutils.

**Comment by ladislas** [comment]
thanks for your investigation @porglezomp 👍
