### ISSUE TITLE
brew install avr-libc no longer works

### ISSUE THREAD

**Issue by jackrsteiner** [osx-cross/homebrew-avr#64]
Hi. I think that the removal of `brew install avr-libc` is intended, as per #54. Would someone just clarify if that's right, and what the correct approach for installing avr-libc now is? Thanks.

**Comment by ladislas** [comment]
@jackrsteiner avr-libc is now part of the whole `avr-gcc` formula.

to install: `$ brew install avr-gcc`

thanks to this, you can now have different versions of avr-gcc installed at the same time.
