### ISSUE TITLE
Conflict of avr-gcc with gcc@7 from homebrew tap

### ISSUE THREAD

**Issue by guneemwelloeux** [osx-cross/homebrew-avr#67]
Hi,

I just installed avr-gcc@7 and the install failed at the linking stage:
```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink lib/gcc/7/libcc1.0.so
Target /usr/local/lib/gcc/7/libcc1.0.so
```

In fact, I already had gcc@7 installed, and this is the reason for the clash.
Wouldn't it be possible to add a dependency from avr-gcc to gcc@7 instead of recompiling gcc in the avr-gcc formula?

Thanks
Will

**Comment by ladislas** [comment]
Thanks for reporting that. I'll look into it.

> Wouldn't it be possible to add a dependency from avr-gcc to gcc@7 instead of recompiling gcc in the avr-gcc formula?

No because avr-gcc is compiled with a specific target (avr) which is not the case with vanilla gcc.

**Comment by leojrfs** [comment]
I can confirm this issue

**Comment by ladislas** [comment]
are you sure you have pulled the latest version of the formula?

a similar issue was reported here #41 and the solution was found here: https://github.com/osx-cross/homebrew-avr/commit/50b95f3884c0ce0f450d489cb1a443282f1567b5

**Comment by guneemwelloeux** [comment]
brew update said everything was up to date, so I believe I am using the latest version. I don't have access to my macbook at the moment, but I'll try and give more info tonight, in particular to make sure I have installed gcc7 from the correct tap, and using the latest formula.

**Comment by ladislas** [comment]
I've found the issue. The path to libdir used by avr-gcc is `../gcc/..` that's why it's conflicting.

i'll update the formula asap.

**Comment by guneemwelloeux** [comment]
If I understood the formula correctly, that means that we'll be able to live with both toolchains installed and brew-linked simultaneously, which is just perfect.
Thanks for the speedy resolution!

**Comment by ladislas** [comment]
just merged it

**Comment by guneemwelloeux** [comment]
I ran `brew update` just now, but it is not reporting avr-gcc as being updated. Do I need to force remove and install again?

**Comment by leojrfs** [comment]
brew update and then brew reinstall it

**Comment by ladislas** [comment]
@guneemwelloeux you can `brew remove` before if needed.

**Comment by guneemwelloeux** [comment]
Everything worked fine after the reinstall, thank you for the fix!
