### ISSUE TITLE
Cannot compile with Arduino IDE and avr-gcc 8.2.0

### ISSUE THREAD

**Issue by HippocampusGirl** [osx-cross/homebrew-avr#84]
I'm having an issue with building an Arduino app from the IDE. I get the following output:

```
...
"/usr/local/bin/avr-g++" -c -g -O3 -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -flto -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   "-I/Users/lw/Library/Arduino15/packages/arduino/hardware/avr/1.6.21/cores/arduino" "-I/Users/lw/Library/Arduino15/packages/arduino/hardware/avr/1.6.21/variants/mega" "/Users/lw/Library/Arduino15/packages/arduino/hardware/avr/1.6.21/cores/arduino/new.cpp" -o "/var/folders/sv/1y3fb14n0tq0l80pmmbpjpmm0000gn/T/arduino_build_701954/core/new.cpp.o"

"/usr/local/bin/avr-gcc-ar" rcs  "/var/folders/sv/1y3fb14n0tq0l80pmmbpjpmm0000gn/T/arduino_build_701954/core/core.a" "/var/folders/sv/1y3fb14n0tq0l80pmmbpjpmm0000gn/T/arduino_build_701954/core/wiring_pulse.S.o"
/usr/local/bin/avr-gcc-ar: Cannot find binary 'avr-ar'
exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.
```

However, the error does not happen when I run the failed command in the terminal. I would appreciate any ideas or feedback, maybe I need to move folders around? Thank you!

**Comment by ladislas** [comment]
I'm not sure I understand. 

If you are trying to compile from the IDE with avr-gcc installed from homebrew it's not going to work.
The IDE ships its own version of avr-gcc and trying to use a different one will break stuff. You don't want to dive into that as they have their own logic of f*cking things up and doing it their way.

My advice is:

- drop the Arduino IDE completely, it's a very poor IDE (but you still need it installed if you want to write Arduino code)
- move to SublimeText, Atom, Visual Code or even vim/neovim
- install the toolchain with homebrew
- use [sudar's Arduino-makefile](https://github.com/sudar/Arduino-Makefile)
- or use my [Bare-Arduino-Project](https://github.com/ladislas/Bare-Arduino-Project)

That way you'll be able to organize your projects freely and build better habits.
