### ISSUE TITLE
avarice install fails due to unnecessary chdir

### ISSUE THREAD

**Issue by Gadroc** [osx-cross/homebrew-avr#86]
When building on Mac OS Mojave avarice fails after fetching source code with the following error:

Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ dir_chdir - avarice

Removing the chdir avarice lines from the avarice.rb file fixes the issue.

**Comment by ladislas** [comment]
I'm not sure I understand. Can you make a pull request with the changes please?

**Comment by ladislas** [comment]
No updates here, closing the issue for now. Feel free to reopen if the problem persists.

**Comment by ladislas** [comment]
@Gadroc I've made the changes you asked and it's working again, thanks for your help! 👍
