### ISSUE TITLE
Install infinite loop

### ISSUE THREAD

**Issue by jpsecher** [osx-cross/homebrew-avr#89]
`brew -v install avr-gcc` never finishes, but seems to infinitely go through the compilations that follow:

    # Now that we have built all the objects, we need to copy
    # them back to the GCC directory.  Too many things (other
    # in-tree libraries, and DejaGNU) know about the layout
    # of the build tree, for now.
    ...

Version info:

    $ sw_vers
    ProductName:    Mac OS X
    ProductVersion: 10.14.2
    BuildVersion:   18C54

    $ /usr/bin/xcodebuild -version
    Xcode 10.1
    Build version 10B61

    $ brew --version
    Homebrew 1.9.2
    Homebrew/homebrew-core (git revision 9d102; last commit 2019-01-20)
    Homebrew/homebrew-cask (git revision 1cb69; last commit 2019-01-21)

    $ brew tap 
    armmbed/formulae
    crisidev/chunkwm
    homebrew/cask
    homebrew/cask-versions
    homebrew/core
    koekeishiya/formulae
    osx-cross/avr

**Comment by jpsecher** [comment]
Sorry, it is not an infinite loop, it just just takes a looong time:

    /usr/local/Cellar/avr-gcc/8.2.0: 1,720 files, 200.3MB, built in 27 minutes

**Comment by ladislas** [comment]
yes, depending on your system it can take from 10min to 1hour.
